application/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'application'
urlpatterns = [
    path('upload', login_required(views.UploadView.as_view(), login_url = '/admin/login/'), name = 'upload'),
    path('success', views.SuccessView.as_view(), name = 'success'),
    path('', views.IndexView.as_view(), name = 'index'),
]

webappcourse/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
]

application/models.py
from django.db import models

# Create your models here.
class Application(models.Model):
    name = models.CharField(max_length = 128)
    surname = models.CharField(max_length = 128)

    phone = models.CharField(max_length = 128)

    applied_at = models.DateTimeField(auto_now_add = True)

    def __str__(self) -> str:
        return f'{self.name} {self.surname}'

    def row(self) -> list:
        return [self.name, self.surname, self.phone, self.applied_at]

application/forms.py
import django.forms as forms

from . import models

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = models.Application

        exclude = ('applied_at', )

        widgets = {
            'name' : forms.TextInput(attrs = {'class': 'input100', 'placeholder' : 'Имя', 'data-validate' : 'Это поле обязательно'}),
            'surname' : forms.TextInput(attrs = {'class': 'input100', 'placeholder' : 'Фамилия', 'data-validate' : 'Это поле обязательно'}),
            'phone' : forms.TextInput(attrs = {'class': 'input100', 'placeholder' : 'Контактный телефон', 'data-validate' : 'Это поле обязательно'}),
        }

        labels = {
            'name' : 'Имя',
            'surname' : 'Фамилия',
            'phone' : 'Контактный телефон',
        }

        # help_texts = {
        #     '' : '',
        # }

        error_messages = {
            'name' : {'max_length': 'Слишком много символов в поле \'Имя\''},
            'surname' : {'max_length': 'Слишком много символов в поле \'Фамилия\''},
            'phone' : {'max_length': 'Слишком много символов в поле \'Контактный телефон\''},
        }

application/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.template import loader, Context

from typing import Union

import openpyxl as xl
import datetime

from . import models
from . import forms 

class SuccessView(View):
    template = 'application/success.html'

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        return render(request = request, template_name = self.template)

class IndexView(View):
    redirect_to = 'success'
    form_template = 'application/index.html'
    model = models.Application
    form = forms.ApplicationForm

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = self.form()

        return render(
            request = request,
            template_name = self.form_template,
            context = {'form': form}
        )

    def post(self, request: HttpRequest, *args, **kwargs) -> Union[HttpResponse, HttpResponseRedirect]:
        form = self.form(data = request.POST)

        is_valid = form.is_valid()
        if is_valid:
            form.save()
            return HttpResponseRedirect(
                redirect_to = self.redirect_to
            )

        return render(
            request = request,
            status = 400,
            template_name = self.form_template,
            context = {'form': form}
        )

class UploadView(View):
    filename_template = 'applications-{date}.xlsx'
    model = models.Application
    title = 'Applications'
    header = ('name', 'surname', 'phone', 'applied_at')

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        response = HttpResponse(content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        filename = self.filename_template.format(date = datetime.datetime.now().strftime('%Y-%m-%d'))
        response['Content-Disposition'] = f'attachment; filename="{filename}"'

        workbook = xl.Workbook()
        worksheet = workbook.active
        worksheet.title = self.title

        r_num = 1
        for c_num, c_header in enumerate(self.header, 1):
            cell = worksheet.cell(row = r_num, column = c_num, value = c_header)

        data = [row.row() for row in self.model.objects.all()]

        for data_row in data:
            r_num += 1
            for c_num, value in enumerate(data_row, 1):
                cell = worksheet.cell(row = r_num, column = c_num, value = value)

        workbook.save(response)
        return response

application/templates/application/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Подача заявок</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--===============================================================================================-->    
            <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/vendor/bootstrap/css/bootstrap.min.css'%}">
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/vendor/animate/animate.css'%}">
        <!--===============================================================================================-->    
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/vendor/css-hamburgers/hamburgers.min.css'%}">
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/vendor/animsition/css/animsition.min.css'%}">
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/vendor/select2/select2.min.css'%}">
        <!--===============================================================================================-->    
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/vendor/daterangepicker/daterangepicker.css'%}">
        <!--===============================================================================================-->
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/css/util.css'%}">
            <link rel="stylesheet" type="text/css" href="{% static 'application/login10/css/main.css'%}">
        <!--===============================================================================================-->
    
        {% block head %}
        {% endblock head %}
    </head>

    <body>
        {% block body %}
        {% endblock body %}
    </body>

<!--===============================================================================================-->
    <script src="{% static 'application/login10/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'application/login10/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'application/login10/vendor/bootstrap/js/popper.js'%}"></script>
    <script src="{% static 'application/login10/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'application/login10/vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'application/login10/vendor/daterangepicker/moment.min.js'%}"></script>
    <script src="{% static 'application/login10/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'application/login10/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'application/login10/js/main.js'%}"></script>
</html>

application/templates/application/custom_tags/custom_render.html
{% for error in form.non_field_error %}
    {% for error in field.erros %}
        <div class = "">
            {{ error }}
        </div>
    {% endfor %}
{% endfor %}

{% for field in form %}
<div class="wrap-input100 validate-input m-b-16">
    {{ field }}
    <span class="focus-input100"></span>
    {% if field.errors %}
        {% for error in field.erros %}
        <div class = "">
            {{ error }}
        </div>
        {% endfor %}
    {% endif %}
</div>
{% endfor %}

application/templates/application/index.html
{% extends 'application/base.html' %}
{% load extras %}

{% block body %}
    {% if form %}
    <div class = 'limiter'>
        <div class = 'container-login100'>
            <div class="wrap-login100 p-t-50 p-b-90">
                <form class = "login100-form validate-form flex-sb flex-w" action = "{% url 'application:index' %}" method = "post">
                    {% csrf_token %}

                    <span class="login100-form-title p-b-51">Подать заявку</span>
                    {% custom_render form %}

                    {% if user.is_authenticated and user.is_staff %}
                    <div class="flex-sb-m w-full p-t-3 p-b-24">
                        <a class="txt1" href="{% url 'application:upload' %}">Загрузить данные</a>
                    </div>
                    {% endif %}

                    <div class="container-login100-form-btn m-t-17">
                        <button class="login100-form-btn">
                            Отправить
                        </button>
                    </div>
                <form>
            </div>
        </div>
    </div>
    
    <div id="dropDownSelect1"></div>
    {% else %}
        <h4>На сервере произошла ошибка</h4>
    {% endif %}
{% endblock body %}

application/templates/application/success.html
{% extends 'application/base.html' %}

{% block body %}
    <div class = 'limiter'>
        <div class = 'container-login100'>
            <div class="wrap-login100 p-t-50 p-b-90">
                <div class = "login100-form validate-form flex-sb flex-w">

                    <span class="login100-form-title p-b-51">Спасибо за заявку</span>
                    
                    <span class="login100-form-title p-b-51">
                        <a href="{% url 'application:index' %}">Вернуться к форме</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}